server:
  port: 8093

spring:
  application:
    name: payment-service

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/demo
    username: demouser
    password: demouser
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  cloud:
    loadbalancer:
      ribbon:
        enable: false
  sql:
    init:
      mode: always

  kafka:
    bootstrap-servers: kafkaserver:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8088/eureka
  instance:
    hostname: payment-service