server:
  port: 8086

spring:
  application:
    name: gateway-server
    
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates: 
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<path>.*), /$\{path}

        - id: product-service
          uri: lb://product-service
          predicates: 
            - Path=/product-service/**
          filters:
            - RewritePath=/product-service/(?<path>.*), /$\{path}

        - id: cart-service
          uri: lb://cart-service
          predicates: 
            - Path=/cart-service/**

        - id: order-service
          uri: lb://order-service
          predicates: 
            - Path=/order-service/**
        
        - id: payment-service
          uri: lb://payment-service
          predicates: 
            - Path=/payment-service/**

eureka:
  instance:
    preferIpAddress: true
    hostname: gateway-server
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8088/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"