server:
  port: 8086

spring:
  application:
    name: gateway-server
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user

        - id: product-service
          uri: lb://product

        - id: cart-service
          uri: lb://cart

        - id: order-service
          uri: lb://order
        
        - id: payment-service
          uri: lb://payment

        



eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8088/eureka