server:
  port: 8086

spring:
  application:
    name: gateway-server
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user
          predicates: 
            - Path=/user/**

        - id: product-service
          uri: lb://product
          predicates: 
            - Path=/product/**

        - id: cart-service
          uri: lb://cart
          predicates: 
            - Path=/cart/**

        - id: order-service
          uri: lb://order
          predicates: 
            - Path=/order/**
        
        - id: payment-service
          uri: lb://payment
          predicates: 
            - Path=/payment/**

        



eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8088/eureka