spring:
  application:
    name: mock-payment-gateway-service
  profiles:
    active: docker
  kafka:
    bootstrap-servers: kafkaserver:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8088/eureka