spring:
  application:
    name: mock-payment-gateway-service
  profiles:
    active: dev
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka