

server:
  port: 8085

spring:
  application:
    name: config-server

  cloud:
    config:
      enabled: false
      server:
        git:
          uri: https://github.com/swapnilpratapsingh-dev/microservicedemo.git
          searchPaths: config/eureka-server
          default-label: config-server-property-files

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka
